---
title: "PLL"
output: html_document
---

```{r}
install.packages("devtools")
devtools::install_github("opisthokonta/goalmodel")
```

```{r}
library(goalmodel)
library(dplyr) # Useful for data manipulation. 
```



```{r}
edit<-function(data){data<-data[,c(2:7)]
names(data)<-c("Date","home","visitor","hgoal","vgoal","result")   
data[order(data$Date,decreasing=TRUE),]
return(data)}
```
```{r}
edit_time<-function(data){
  data$Date<-as.character((data$Date))
  if (nchar(data$Date[1])==8){
data$Date<-paste("20",substr(data$Date,7,8),substr(data$Date,3,6),substr(data$Date,1,2),sep = "")
  }
  else{data$Date<-paste(substr(data$Date,7,10),substr(data$Date,3,6),substr(data$Date,1,2),sep = "")}
return(data)
}
```
```{r}
xi<-function(data,predict){
  
sum_xi=0
for (i in 1:dim(data)[1]){
if (data[i,]$result=="H"){
sum_xi=sum_xi+log(predict$p1[i])}
else if (data[i,]$result=="A"){
sum_xi=sum_xi+log(predict$p2[i])}
else{sum_xi=sum_xi+log(predict$pd[i])}
}
return(sum_xi)}
```

```{r}
data1213<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1314.csv")))
data1314<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1314.csv")))
data1415<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1415.csv")))[1:380,]
data1516<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1516.csv")))
data1617<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1617.csv")))
data1718<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1718.csv")))
data1819<-edit_time(edit(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1819.csv")))
#data<-rbind(data1415,data1516,data1617)
#data<-data1617
data1415_n<-edit_time(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1415.csv"))[1:380,]
data1516_n<-edit_time(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1516.csv"))
data1617_n<-edit_time(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1617.csv"))
data1718_n<-edit_time(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1718.csv"))
data1819_n<-edit_time(read.csv("C:\\Users\\lidai\\Desktop\\Football\\1819.csv"))
#View(data)

```


```{r}
#input data
k<-100
s<-5


sum_xi<-0
data<-rbind(data1213,data1314,data1415)
train_data<-data[1:(dim(data)[1]-k),]
test_data<-data[(dim(data)[1]-k+1):dim(data)[1],]

while (!(is.null(test_data))){
my_weights <- weights_dc(train_data$Date, xi=0.0044)

gm_res_dc <- goalmodel(goals1 = train_data$hgoal, goals2 = train_data$vgoal,
                     team1 = train_data$home, team2=train_data$visitor,dc=TRUE,
           weights = my_weights)

if (dim(test_data)[1]>s){
  predict<-predict_result(gm_res_dc, team1=test_data[1:s,]$home, team2=test_data[1:s,]$visitor, return_df = TRUE)
sum_xi<-sum_xi+xi(test_data[1:s,],predict)
train_data<-rbind(train_data,test_data[1:s,])
test_data<-test_data[(s+1):dim(test_data)[1],]}

else{
   predict<-predict_result(gm_res_dc, team1=test_data$home, team2=test_data$visitor, return_df = TRUE)
sum_xi<-sum_xi+xi(test_data,predict)
train_data<-rbind(train_data,test_data)
test_data<-c()}
}
sum_xi


```
